spring:
  application:
    name: Techmaster
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
auth:
  jwt:
    secret: ${JWT_SECRET}