spring:
  application:
    name: Techmaster
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
auth:
  token-lifetime: 600 # 600 minutes
  refresh-lifetime: 43200 # 30 days
  jwt:
    secret: ${JWT_SECRET}
payment:
  vn-pay:
    code: ${VNPAY_TMN_CODE} # merchant code
    secret: ${VNPAY_SECRET_KEY}
    url: ${VNPAY_PAYMENT_URL}
    query-url: ${VNPAY_QUERY_URL}
    callback: ${VNPAY_CALLBACK_URL}
